// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'userlist': string;
  'userlist__title': string;
  'users__quantity': string;
}
export const cssExports: CssExports;
export default cssExports;
