// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loader': string;
  'loader__inner': string;
  'spin': string;
}
export const cssExports: CssExports;
export default cssExports;
