// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'card__btn': string;
  'card__button': string;
  'card__info': string;
}
export const cssExports: CssExports;
export default cssExports;
