// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form__input': string;
  'form__textarea': string;
  'invalid': string;
  'profile': string;
  'profile__btn': string;
  'profile__form': string;
  'profile__info': string;
}
export const cssExports: CssExports;
export default cssExports;
