// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aside': string;
  'aside__title': string;
}
export const cssExports: CssExports;
export default cssExports;
